### ISSUE TITLE
After installation how do I connect to it?

### ISSUE THREAD

**Issue by justinmchase** [helm/kind-action#100]
It shows how to run this action to create a cluster but I need to then have the `kubectl` context configured to interact with the cluster.

The example in the main readme seems to not show that, and I can't seem to find any documentation on it. How does one connect to the cluster after it is created?

**Comment by holomekc** [comment]
You can use:
```sh
kubectl config get-contexts
```

the context seems to be `kind-{cluster_name}`

So when you configure:
```yaml
      - name: Create k8s cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: my-cluster
```

it is `kind-my-cluster`
