### ISSUE TITLE
Creating a cluster with a load balancer

### ISSUE THREAD

**Issue by heruan** [helm/kind-action#137]
I'm trying to get my GitHub Action workflow able to install my Helm chart in KinD and run a test suite against a deployment exposed with an Ingress. I'm using the `helm/kind-action@v1` to install KinD, then I'm installing Ingress NGINX but the controller gets stuck on getting an external IP Address.

From https://kind.sigs.k8s.io/docs/user/loadbalancer/ I understand I might need `cloud-provider-kind` for this to work, but how to use it with `helm/kind-action@v1`? Is there a configuration option to enable it?

**Comment by cpanato** [comment]
you might need to install something like `metal-lb`

**Comment by heruan** [comment]
I was able to run it with the Docker image, like this:

```
      - name: Create KinD cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kind
      - name: Run KinD load-balancer
        run: |
          docker run -d --rm --net=host -v /var/run/docker.sock:/var/run/docker.sock \
            registry.k8s.io/cloud-provider-kind/cloud-controller-manager:v0.6.0
```

It works fine now!
