### ISSUE TITLE
Specifying node image doesn't seem to work using `INPUT_NODE_IMAGE`

### ISSUE THREAD

**Issue by pmalek** [helm/kind-action#141]
### Problem statement

It looks like this action allows callers to specify the node image using the `INPUT_NODE_IMAGE`: https://github.com/helm/kind-action/blob/d730aaf5682e7d9c25245c74b8a105b96decb21a/main.sh#L39-L41 but for some reason this doesn't work when used like so:

```
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - node_image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
        - node_image: kindest/node:v1.31.6@sha256:28b7cbb993dfe093c76641a0c95807637213c9109b761f1d422c2400e22b8e87

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version-file: go.mod

    - name: Create k8s KinD Cluster
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      env:
        INPUT_NODE_IMAGE: ${{ matrix.node_image }}
```

Example: https://github.com/Kong/kubernetes-configuration/actions/runs/14467465328/job/40573095776#step:5:1

```
Run helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3
  with:
    version: v0.27.0
    cluster_name: chart-testing
    wait: 60s
    verbosity: 0
    kubectl_version: v1.31.4
    registry: false
    registry_image: registry:2
    registry_name: kind-registry
    registry_port: 5000
    registry_enable_delete: false
    ignore_failed_clean: false
  env:
    MISE_LOG_LEVEL: info
    MISE_TRUSTED_CONFIG_PATHS: /home/runner/work/kubernetes-configuration/kubernetes-configuration
    MISE_YES: 1
    INPUT_NODE_IMAGE: kindest/node:v1.31.6@sha256:28b7cbb993dfe093c76641a0c95807637213c9109b761f1d422c2400e22b8e87
Installing kind...
/opt/hostedtoolcache/kind/v0.27.0/amd64/kind/bin ~/work/kubernetes-configuration/kubernetes-configuration
kind-linux-amd64: OK
~/work/kubernetes-configuration/kubernetes-configuration
Adding kind directory to PATH...
Installing kubectl...
Adding kubectl directory to PATH...
kind v0.27.0 go1.23.6 linux/amd64
Client Version: v1.31.4
Kustomize Version: v5.4.2
Creating kind cluster...
Creating cluster "chart-testing" ...
 • Ensuring node image (kindest/node:v1.32.2) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.32.2) 🖼
 • Preparing nodes 📦   ...
 ✓ Preparing nodes 📦
```

**Comment by pmalek** [comment]
It seems that I missed the `node_image` param which does the job.


```
    - name: Create k8s KinD Cluster
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      with:
        node_image: ${{ matrix.node_image }}
```

Closing.
