### ISSUE TITLE
Support KIND running inside container

### ISSUE THREAD

**Issue by axsaucedo** [helm/kind-action#30]
Currently we have KIND running in our Kubernetes CI, where KIND runs inside of a pod/container, which requires the following mounts with the node:
```
                volumeMounts:
                  - mountPath: /lib/modules
                    name: modules
                    readOnly: true
                  - mountPath: /sys/fs/cgroup
                    name: cgroup
                  - name: dind-storage
                    mountPath: /var/lib/docker
                securityContext:
                  privileged: true
                imagePullPolicy: Always
              volumes:
                - name: modules
                  hostPath:
                    path: /lib/modules
                    type: Directory
                - name: cgroup
                  hostPath:
                    path: /sys/fs/cgroup
                    type: Directory
                - name: dind-storage
                  emptyDir: {}
```

When running a KIND docker action inside a KIND enabled container (which works on kubernetes) such as:
```
...
    runs-on: ubuntu-18.04
    container: repo/container:tag
...
```
It seems to work when running it locally using `act` (https://github.com/nektos/act), but when running it on the github Actions worker, I get the error `Error: Kubernetes cluster unreachable: Get https://127.0.0.1:34221/version?timeout=32s: dial tcp 127.0.0.1:34221: connect: connection refused`.

The KIND cluster does seem to get correctly created, but the issue seems to mainly be that the cluster is not reachable. Is this an issue that you have come across before?

**Comment by gopisaba** [comment]
I have same issue. The issue looks like the nodeport for KinD api server (in your case `34221`) is not exposed to the runner container. So it is failing to connect to the cluster.

**Comment by svatwork** [comment]
Any new insights @axsaucedo?

**Comment by axsaucedo** [comment]
No, it still doesn't work unfortunately - at least to my knowledge

**Comment by svatwork** [comment]
Thanks for the quick reply.

Then I am considering to create a self-hosted runner, unless I have some buy-in from my team to continue debugging, I'll keep you updated.

**Comment by axsaucedo** [comment]
Ok, yeah it would be great to hear your thoughts. We actually use KIND on our JX cluster where we run CI jobs, we were looking at migrating, but even if this support was added, we would reach the limits of the default runners very fast on memory and disk space due to the images required, so at least for now we've decided to stick with our current setup.

**Comment by svatwork** [comment]
I was able to solve it, the tools provided by Github Actions proved to be sufficient. 

> The issue looks like the nodeport for KinD api server (in your case 34221) is not exposed to the runner container. So it is failing to connect to the cluster.

So yes, you need to configure the user-defined network by Github. E.g.: 

kind-config.yaml:

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: '127.0.0.1'
  apiServerPort: 6443
```

Github Actions workflow:

```sh
export KUBECONFIG=$HOME/.kube/config # if not already set 
export KIND_EXPERIMENTAL_DOCKER_NETWORK=${{ job.container.network }}

kind create cluster \
            --kubeconfig $KUBECONFIG \
            --config=./kind-config.yaml

kubectl config set-cluster kind-kind --server=https://kind-control-plane:6443 
```
