### ISSUE TITLE
config path not found

### ISSUE THREAD

**Issue by bukowa** [helm/kind-action#31]
If my `kind.config.yaml` is located in git root repository in folder `scripts` that won't work:

````yaml
jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          config: ./scripts/kind.config.yaml
````

How can i point the config path to the proper file?
That won't work also: `$GITHUB_WORKSPACE/scripts/kind.config.yaml`
