### ISSUE TITLE
It there a way to use this action on a rootless docker setup?

### ISSUE THREAD

**Issue by marcofranssen** [helm/kind-action#34]
https://kind.sigs.k8s.io/docs/user/rootless/#creating-a-kind-cluster-with-rootless-docker

I have tried following in my workflow:

```
job:
  test:
    env: 
      DOCKER_HOST: unix://${XDG_RUNTIME_DIR}/docker.sock
    steps:
      - name: Create kind v1.19.7 cluster
        uses: helm/kind-action@v1.1.0
        with:
          node_image: kindest/node:v1.19.7
```

However that fails with 

```bash
Run helm/kind-action@v1.1.0
  with:
    node_image: kindest/node:v1.19.7
  env:
    DOCKER_HOST: unix://${XDG_RUNTIME_DIR}/docker.sock
    pythonLocation: /home/runners/actions-runner/_work/_tool/Python/3.7.10/x64
    LD_LIBRARY_PATH: /home/runners/actions-runner/_work/_tool/Python/3.7.10/x64/lib
    CT_CONFIG_DIR: /home/runners/actions-runner/_work/_tool/ct/v3.3.1/x86_64/etc
    VIRTUAL_ENV: /home/runners/actions-runner/_work/_tool/ct/v3.3.1/x86_64/venv
Adding kind directory to PATH...
Adding kubectl directory to PATH...
kind v0.9.0 go1.15.2 linux/amd64
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Creating kind cluster...
ERROR: failed to create cluster: failed to list clusters: command "docker ps -a --filter label=io.x-k8s.kind.cluster=chart-testing --format '{{.Names}}'" failed with error: exit status 1

Command Output: parse unix://${XDG_RUNTIME_DIR}/docker.sock: invalid character "{" in host name
```

I think this action needs to have a parameter to run as rootless so this can be handled within the shell script of this action.
