### ISSUE TITLE
kubectl_version input is advertised in readme but unexpected IRL

### ISSUE THREAD

**Issue by joe-kimmel-vmw** [helm/kind-action#62]
Hello and thanks for this action!

In the readme it is advertised that we can set the [kubectl version](https://github.com/helm/kind-action/blob/main/README.md?plain=1#L24)

However when I run this action on github I see the warning:
`Warning: Unexpected input(s) 'kubectl_version', valid inputs are ['version', 'config', 'node_image', 'cluster_name', 'wait', 'log_level']`

My action looks like:
```
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          version: v0.13.0
          kubectl_version: v1.24.0
          cluster_name: kinder
```

 when I check the versions in my action I see:
```
kubectl version --short
Client Version: v1.20.8
Server Version: v1.24.0
```
which isn't the advertised default version of 1.20.10 (same line/link above into the readme.md) and definitely violates the k8s "version skew" directive since I've selected kind v13 which defaults to k8s 1.24.0. 

Is there a way to set the kubectl version?
