### ISSUE TITLE
Add an option to remove Kind cluster

### ISSUE THREAD

**Issue by brb** [helm/kind-action#86]
I would like to create multiple Kind clusters in the same Github Action workflow. That would require deleting a previously created Kind cluster.

Would you accept a contribution to add a new option to remove a Kind cluster?

Example usage:
```
- name: Create kind cluster #1
  uses: helm/kind-action
    with:
      version: ${{ env.kind_version }}
      config: ${{ env.kind_config }}

- name: Run tests #1
...

- name: Delete kind cluster #1
  uses: helm/kind-action
  with:
     delete: true

- name: Create kind cluster #2
  uses: helm/kind-action
    with:
      version: ${{ env.kind_version }}
      config: ${{ env.kind_config }}

- name: Run tests #2
...
```

An alternative would be to to always delete a Kind cluster before creating a new one, but that might break existing GHA workflows in which multiple clusters are created with different `cluster_name`.

Would you accept such a contribution?
